'I-ASU-23 : C-Calculus1':
    - '\[tags\]:- "(.*[,]?I-ASU-23 : C-Calculus1[,].*)'
S-Calculus:
    - '\[tags\]:- "(.*[,]?S-Calculus[,].*)'
S-Chemistry:
    - '\[tags\]:- "(.*[,]?S-Chemistry[,].*)'
S-Engineering Drawing:
    - '\[tags\]:- "(.*[,]?S-Engineering Drawing[,].*)'
S-History:
    - '\[tags\]:- "(.*[,]?S-History[,].*)'
S-Mechanics:
    - '\[tags\]:- "(.*[,]?S-Mechanics[,].*)'
S-Physics:
    - '\[tags\]:- "(.*[,]?S-Physics[,].*)'
S-Technical English:
    - '\[tags\]:- "(.*[,]?S-Technical English[,].*)'
